function config = load_task_config(configPath, projectRoot)
%LOAD_TASK_CONFIG Load and minimally validate the task's JSON configuration.

if ~isfile(configPath)
    error('ImaginedSpeech:MissingConfig', 'Configuration not found: %s', configPath);
end

config = jsondecode(fileread(configPath));
requiredSections = {'display', 'launcher', 'placeholder', 'block0', 'block1', 'block2', 'block3', 'block4', 'keys', ...
    'photodiode', 'cbmex', 'matcbsdk', 'audio_sync', 'paths'};
for index = 1:numel(requiredSections)
    section = requiredSections{index};
    if ~isfield(config, section)
        error('ImaginedSpeech:InvalidConfig', 'Missing config section: %s', section);
    end
end

if config.schema_version ~= 1
    error('ImaginedSpeech:InvalidConfig', ...
        'Unsupported config schema_version: %g', config.schema_version);
end
if ~isscalar(config.placeholder.duration_seconds) || ...
        ~isfinite(config.placeholder.duration_seconds) || ...
        config.placeholder.duration_seconds <= 0
    error('ImaginedSpeech:InvalidConfig', ...
        'placeholder.duration_seconds must be a positive finite scalar.');
end
if numel(config.display.background_rgb) ~= 3 || ...
        numel(config.display.text_rgb) ~= 3
    error('ImaginedSpeech:InvalidConfig', 'Display colors must be RGB triplets.');
end
if ~isscalar(config.block0.auto_advance_seconds) || ...
        ~isfinite(config.block0.auto_advance_seconds) || ...
        config.block0.auto_advance_seconds < 0
    error('ImaginedSpeech:InvalidConfig', ...
        'block0.auto_advance_seconds must be a finite nonnegative scalar.');
end
if config.block0.horizontal_margin_percent <= 0 || ...
        config.block0.horizontal_margin_percent >= 45
    error('ImaginedSpeech:InvalidConfig', ...
        'block0.horizontal_margin_percent must be between 0 and 45.');
end
if ~isfield(config.keys, 'pause') || strlength(string(config.keys.pause)) == 0
    error('ImaginedSpeech:InvalidConfig', 'keys.pause must be a non-blank key name.');
end
if strcmpi(string(config.keys.pause), string(config.keys.abort))
    error('ImaginedSpeech:InvalidConfig', ...
        'keys.pause must not be the same key as keys.abort, which always means "abort the task".');
end
if ~ismember(string(config.block1.presentation_mode), ["listening", "reading", "both"])
    error('ImaginedSpeech:InvalidConfig', ...
        'block1.presentation_mode must be listening, reading, or both.');
end
if ~isscalar(config.block1.reading_only_word_seconds) || ...
        ~isfinite(config.block1.reading_only_word_seconds) || ...
        config.block1.reading_only_word_seconds <= 0 || ...
        ~isscalar(config.block1.reading_only_phrase_seconds) || ...
        ~isfinite(config.block1.reading_only_phrase_seconds) || ...
        config.block1.reading_only_phrase_seconds <= 0
    error('ImaginedSpeech:InvalidConfig', ...
        'block1 reading-only durations must be positive finite scalars.');
end
if ~isfield(config.block1, 'start_trial') || ~isscalar(config.block1.start_trial) || ...
        ~isfinite(config.block1.start_trial) || config.block1.start_trial < 1 || ...
        config.block1.start_trial ~= fix(config.block1.start_trial)
    error('ImaginedSpeech:InvalidConfig', 'block1.start_trial must be a positive integer.');
end
if ~isscalar(config.block2.image_display_fraction) || ...
        ~isfinite(config.block2.image_display_fraction) || ...
        config.block2.image_display_fraction <= 0 || ...
        config.block2.image_display_fraction > 1
    error('ImaginedSpeech:InvalidConfig', ...
        'block2.image_display_fraction must be in the range (0, 1].');
end
if ~isfield(config.block2, 'start_trial') || ~isscalar(config.block2.start_trial) || ...
        ~isfinite(config.block2.start_trial) || config.block2.start_trial < 1 || ...
        config.block2.start_trial ~= fix(config.block2.start_trial)
    error('ImaginedSpeech:InvalidConfig', 'block2.start_trial must be a positive integer.');
end
if ~isfield(config.block3, 'start_position') || ...
        ~ismember(string(config.block3.start_position), ...
        ["story_1", "comprehension_1", "story_2", "comprehension_2"])
    error('ImaginedSpeech:InvalidConfig', ...
        'block3.start_position must be one of: story_1, comprehension_1, story_2, comprehension_2.');
end
if ~isfield(config.photodiode, 'flash_frames') || ...
        ~isscalar(config.photodiode.flash_frames) || ...
        ~isfinite(config.photodiode.flash_frames) || ...
        config.photodiode.flash_frames < 1 || ...
        config.photodiode.flash_frames ~= fix(config.photodiode.flash_frames)
    error('ImaginedSpeech:InvalidConfig', ...
        'photodiode.flash_frames must be a positive integer (number of refresh frames each sync flash stays on).');
end
if config.cbmex.enabled && config.matcbsdk.enabled
    error('ImaginedSpeech:InvalidConfig', ...
        'cbmex.enabled and matcbsdk.enabled cannot both be true; choose one Cbmex/NSP comment backend.');
end
if ~isfield(config.cbmex, 'use_patient_log') || ~islogical(config.cbmex.use_patient_log)
    error('ImaginedSpeech:InvalidConfig', 'cbmex.use_patient_log must be true or false.');
end
if ~isfield(config.matcbsdk, 'use_patient_log') || ~islogical(config.matcbsdk.use_patient_log)
    error('ImaginedSpeech:InvalidConfig', 'matcbsdk.use_patient_log must be true or false.');
end
if config.matcbsdk.enabled
    if isempty(config.matcbsdk.device_types)
        error('ImaginedSpeech:InvalidConfig', ...
            'matcbsdk.device_types must be a nonempty list of non-blank device type names.');
    end
    deviceTypes = cellstr(config.matcbsdk.device_types);
    if isempty(deviceTypes) || any(cellfun(@(name) isempty(strtrim(name)), deviceTypes))
        error('ImaginedSpeech:InvalidConfig', ...
            'matcbsdk.device_types must be a nonempty list of non-blank device type names.');
    end
    if ~isscalar(config.matcbsdk.callback_queue_depth) || ...
            ~isfinite(config.matcbsdk.callback_queue_depth) || ...
            config.matcbsdk.callback_queue_depth <= 0
        error('ImaginedSpeech:InvalidConfig', ...
            'matcbsdk.callback_queue_depth must be a positive finite scalar.');
    end
end
if config.audio_sync.enabled
    requiredTones = {'block_start', 'block_end', 'pause_on', 'pause_resume', ...
        'block1_reading_stimulus_onset', 'block1_early_response', ...
        'block1_action_cue_onset', 'block1_action_cue_offset', ...
        'block2_image_onset', 'block2_response', 'block3_question_onset', 'block4_question_onset'};
    if ~isscalar(config.audio_sync.sample_rate) || ~isfinite(config.audio_sync.sample_rate) || ...
            config.audio_sync.sample_rate <= 0 || ...
            ~isscalar(config.audio_sync.volume) || ~isfinite(config.audio_sync.volume) || ...
            config.audio_sync.volume <= 0 || config.audio_sync.volume > 1
        error('ImaginedSpeech:InvalidConfig', ...
            'audio_sync.sample_rate must be positive and audio_sync.volume must be in (0, 1].');
    end
    for index = 1:numel(requiredTones)
        toneName = requiredTones{index};
        if ~isfield(config.audio_sync.tones, toneName)
            error('ImaginedSpeech:InvalidConfig', ...
                'audio_sync.tones is missing required tone: %s', toneName);
        end
        tone = config.audio_sync.tones.(toneName);
        if ~isfield(tone, 'frequency_hz') || ~isfield(tone, 'duration_ms') || ...
                ~isscalar(tone.frequency_hz) || ~isfinite(tone.frequency_hz) || tone.frequency_hz <= 0 || ...
                ~isscalar(tone.duration_ms) || ~isfinite(tone.duration_ms) || tone.duration_ms <= 0
            error('ImaginedSpeech:InvalidConfig', ...
                'audio_sync.tones.%s must have a positive frequency_hz and duration_ms.', toneName);
        end
        if isfield(tone, 'volume') && (~isscalar(tone.volume) || ~isfinite(tone.volume) || ...
                tone.volume <= 0 || tone.volume > 1)
            error('ImaginedSpeech:InvalidConfig', ...
                'audio_sync.tones.%s.volume, when given, must be in the range (0, 1].', toneName);
        end
    end
end

config.project_root = projectRoot;
config.paths.task_data = fullfile(projectRoot, config.paths.task_data);
config.paths.output = fullfile(projectRoot, config.paths.output);
if ~isfolder(config.paths.patient_data) && ~isfile(config.paths.patient_data)
    % Preserve absolute configured paths; relative paths are project-rooted.
    if ~isAbsolutePath(config.paths.patient_data)
        config.paths.patient_data = fullfile(projectRoot, config.paths.patient_data);
    end
end
config.block0.content_file = fullfile(config.paths.task_data, ...
    config.block0.content_file);
config.block1.content_file = fullfile(config.paths.task_data, ...
    config.block1.content_file);
config.block2.content_file = fullfile(config.paths.task_data, ...
    config.block2.content_file);
config.block3.content_file = fullfile(config.paths.task_data, ...
    config.block3.content_file);
config.block4.content_file = fullfile(config.paths.task_data, ...
    config.block4.content_file);
end

function tf = isAbsolutePath(pathValue)
tf = ~isempty(regexp(char(pathValue), '^[A-Za-z]:[\\/]|^\\\\', 'once'));
end
