function [blockNumber, patientId] = select_task_block(launcherConfig)
%SELECT_TASK_BLOCK Show a modal experimenter GUI for Blocks 0 through 4.

blockNumber = [];
patientId = '';
labels = { ...
    'Block 0 - Instructions', ...
    'Block 1 - Stories', ...
    'Block 2 - Speech / Imagery', ...
    'Block 3 - Image Encoding', ...
    'Block 4 - VVIQ Survey'};

window = figure( ...
    'Name', launcherConfig.title, ...
    'NumberTitle', 'off', ...
    'MenuBar', 'none', ...
    'ToolBar', 'none', ...
    'Resize', 'off', ...
    'Position', launcherConfig.position(:)', ...
    'CloseRequestFcn', @closeLauncher);

uicontrol(window, 'Style', 'text', 'String', 'Patient ID', ...
    'FontSize', 11, 'HorizontalAlignment', 'left', ...
    'Position', [50, 350, 100, 22]);
patientField = uicontrol(window, 'Style', 'edit', 'String', '', ...
    'FontSize', 12, 'HorizontalAlignment', 'left', ...
    'Position', [150, 346, 220, 30]);
statusText = uicontrol(window, 'Style', 'text', 'String', '', ...
    'ForegroundColor', [0.75, 0, 0], 'HorizontalAlignment', 'center', ...
    'Position', [40, 8, 340, 24]);

for index = 1:numel(labels)
    y = 292 - (index - 1) * 52;
    uicontrol(window, ...
        'Style', 'pushbutton', ...
        'String', labels{index}, ...
        'FontSize', 12, ...
        'Position', [50, y, 320, 38], ...
        'Callback', @(~, ~) chooseBlock(index - 1));
end

uiwait(window);
if isgraphics(window)
    delete(window);
end

    function chooseBlock(selection)
        candidate = strtrim(get(patientField, 'String'));
        if isempty(regexp(candidate, '^[A-Za-z0-9_-]+$', 'once'))
            set(statusText, 'String', ...
                'Enter a Patient ID using letters, numbers, _ or -.');
            return;
        end
        patientId = candidate;
        blockNumber = selection;
        uiresume(window);
    end

    function closeLauncher(~, ~)
        blockNumber = [];
        patientId = '';
        uiresume(window);
    end
end
